spring:
  r2dbc:
    pool:
      enabled: true
    url: r2dbc:mysql://localhost:3306/reactive
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9090
